// Poly-Cam 0.1.9. Generated by npm run build; edit src/ instead.

// src/main.mod.js
import { PolyMod, MixinType } from "https://cdn.polymodloader.com/cb/polytrackmods/PolyModLoader/0.6.3/PolyTypes.js";

// src/math.js
var clamp = (value, min, max) => Math.max(min, Math.min(max, value));
var smoothstep = (t) => t * t * (3 - 2 * t);
function rotateVector(out, x, y, z, q) {
  const qx = q.x, qy = q.y, qz = q.z, qw = q.w;
  const ix = qw * x + qy * z - qz * y;
  const iy = qw * y + qz * x - qx * z;
  const iz = qw * z + qx * y - qy * x;
  const iw = -qx * x - qy * y - qz * z;
  out.x = ix * qw + iw * -qx + iy * -qz - iz * -qy;
  out.y = iy * qw + iw * -qy + iz * -qx - ix * -qz;
  out.z = iz * qw + iw * -qz + ix * -qy - iy * -qx;
  return out;
}
function localPoint(out, position, quaternion, x, y, z) {
  rotateVector(out, x, y, z, quaternion);
  out.x += position.x;
  out.y += position.y;
  out.z += position.z;
  return out;
}
function finiteVector(v) {
  return Number.isFinite(v.x) && Number.isFinite(v.y) && Number.isFinite(v.z);
}

// src/rigs.js
var MODES = [
  "Cinematic Chase",
  "Low Chase",
  "Front Chase",
  "Side Tracking",
  "Orbit Cam",
  "Drone Cam",
  "Trackside Cam",
  "Fly-By Cam",
  "Vehicle Mount",
  "Freecam"
];
var point = (x = 0, y = 0, z = 0) => ({ x, y, z });
var CameraRig = class {
  constructor(name) {
    this.name = name;
  }
  compose(context, runtime, out) {
    return out;
  }
};
var ChaseRig = class extends CameraRig {
  constructor(low = false) {
    super(low ? "Low Chase" : "Cinematic Chase");
    this.low = low;
  }
  compose({ position, quaternion, speed }, runtime, out) {
    const speedScale = clamp(speed / 220, 0, 1);
    const shot = runtime.montageShot;
    const distance = shot?.distance ?? (this.low ? 7 + speedScale * 1.3 : 8.5);
    const height = shot?.height ?? (this.low ? 0.85 : 2.15);
    localPoint(out.position, position, quaternion, shot?.lateral ?? (this.low ? 0.18 : 0.25), height, -distance);
    localPoint(out.target, position, quaternion, 0, this.low ? 0.55 : 1.1, (shot?.lookAhead ?? 3.4) + speedScale * 2.5);
    out.fov = runtime.fov + (this.low ? 7 : 0) + Math.min(5, speedScale * 4);
    out.positionSharpness = this.low ? 5.5 : 3.4;
    out.targetSharpness = 6;
    out.rotationSharpness = 7;
    return out;
  }
};
var FrontChaseRig = class extends CameraRig {
  constructor() {
    super("Front Chase");
  }
  compose({ position, quaternion }, runtime, out) {
    localPoint(out.position, position, quaternion, 0, runtime.montageShot?.height ?? 2.2, runtime.montageShot?.distance ?? 9);
    localPoint(out.target, position, quaternion, 0, 1, -0.4);
    out.fov = runtime.fov;
    out.positionSharpness = 3;
    out.targetSharpness = 7;
    out.rotationSharpness = 7;
    return out;
  }
};
var SideTrackingRig = class extends CameraRig {
  constructor() {
    super("Side Tracking");
  }
  compose({ position, quaternion }, runtime, out) {
    const shot = runtime.montageShot;
    localPoint(out.position, position, quaternion, runtime.side * (shot?.distance ?? 8), shot?.height ?? 2.2, shot?.longitudinal ?? runtime.longitudinal);
    localPoint(out.target, position, quaternion, 0, 0.9, 0.3);
    out.fov = runtime.fov;
    out.positionSharpness = 3;
    out.targetSharpness = 6;
    out.rotationSharpness = 7;
    return out;
  }
};
var OrbitRig = class extends CameraRig {
  constructor() {
    super("Orbit Cam");
  }
  compose({ position, quaternion, dt }, runtime, out) {
    const shot = runtime.montageShot;
    runtime.orbitAngle += dt * (shot?.orbitSpeed ?? runtime.orbitSpeed) * (shot?.side ?? runtime.orbitDirection);
    const x = Math.sin(runtime.orbitAngle) * (shot?.radius ?? runtime.orbitRadius);
    const z = Math.cos(runtime.orbitAngle) * (shot?.radius ?? runtime.orbitRadius);
    localPoint(out.position, position, quaternion, x, shot?.height ?? runtime.orbitHeight, z);
    localPoint(out.target, position, quaternion, 0, 1, 0);
    out.fov = runtime.fov;
    out.positionSharpness = 2.3;
    out.targetSharpness = 4;
    out.rotationSharpness = 5;
    return out;
  }
};
var DroneRig = class extends CameraRig {
  constructor() {
    super("Drone Cam");
  }
  compose({ position, quaternion }, runtime, out) {
    const shot = runtime.montageShot;
    const forwardX = 2 * (quaternion.x * quaternion.z + quaternion.w * quaternion.y);
    const forwardZ = 1 - 2 * (quaternion.x * quaternion.x + quaternion.y * quaternion.y);
    const length = Math.hypot(forwardX, forwardZ);
    const trail = shot?.trail ?? 5;
    out.position.x = position.x - (length > 0.01 ? forwardX / length : 0) * trail;
    out.position.y = position.y + (shot?.altitude ?? runtime.droneAltitude);
    out.position.z = position.z - (length > 0.01 ? forwardZ / length : 1) * trail;
    localPoint(out.target, position, quaternion, 0, 0.9, 2);
    out.fov = runtime.fov;
    out.positionSharpness = 1.6;
    out.targetSharpness = 4.5;
    out.rotationSharpness = 4;
    return out;
  }
};
var TracksideRig = class extends CameraRig {
  constructor() {
    super("Trackside Cam");
  }
  compose({ position }, runtime, out) {
    const shot = runtime.montageShot;
    if (!shot?.anchor && !runtime.tracksidePlaced) {
      runtime.trackside.x = position.x + 12;
      runtime.trackside.y = position.y + 4;
      runtime.trackside.z = position.z + 18;
      runtime.tracksideLook.x = position.x;
      runtime.tracksideLook.y = position.y + 0.75;
      runtime.tracksideLook.z = position.z;
      runtime.tracksidePlaced = true;
    }
    const anchor = shot?.anchor || runtime.trackside;
    out.position.x = anchor.x;
    out.position.y = anchor.y;
    out.position.z = anchor.z;
    if (!shot && runtime.tracksideFixed) {
      out.target.x = runtime.tracksideLook.x;
      out.target.y = runtime.tracksideLook.y;
      out.target.z = runtime.tracksideLook.z;
    } else {
      out.target.x = position.x;
      out.target.y = position.y + 0.75;
      out.target.z = position.z;
    }
    out.fov = runtime.fov;
    out.positionSharpness = 100;
    out.targetSharpness = shot ? 100 : runtime.tracksideFixed ? 100 : runtime.panSharpness;
    out.rotationSharpness = shot ? 30 : runtime.tracksideFixed ? 100 : runtime.panSharpness;
    return out;
  }
};
var FlyByRig = class extends CameraRig {
  constructor() {
    super("Fly-By Cam");
  }
  compose({ position, quaternion, dt }, runtime, out) {
    runtime.flybyClock += dt;
    const phase = runtime.flybyClock % 7;
    const shot = runtime.montageShot;
    if (!shot?.anchor && (phase < 0.12 || runtime.flybyAnchor === null)) {
      localPoint(runtime.flybyAnchor = runtime.flybyAnchor || point(), position, quaternion, runtime.flybySide * 5, 2.8, runtime.flybyDistance);
    }
    const anchor = shot?.anchor || runtime.flybyAnchor;
    out.position.x = anchor.x;
    out.position.y = anchor.y;
    out.position.z = anchor.z;
    out.target.x = position.x;
    out.target.y = position.y + 0.7;
    out.target.z = position.z;
    out.fov = runtime.fov - 8;
    out.positionSharpness = 100;
    out.targetSharpness = shot ? 100 : phase > 4.8 ? 1.8 : 8;
    out.rotationSharpness = shot ? 30 : phase > 4.8 ? 2.5 : 9;
    return out;
  }
};
var VehicleMountRig = class extends CameraRig {
  constructor() {
    super("Vehicle Mount");
  }
  compose({ position, quaternion }, runtime, out) {
    const mounts = {
      "Front bumper": [0, 0.55, 2.3],
      "Rear bumper": [0, 0.65, -2.2],
      "Bonnet": [0, 1.05, 0.8],
      "Roof": [0, 1.85, 0.2],
      "Front-left wheel": [-0.75, 0.15, 1.2],
      "Front-right wheel": [0.75, 0.15, 1.2],
      "Rear wheel": [0.72, 0.18, -1.35]
    };
    const offset = mounts[runtime.mount] || mounts.Roof;
    localPoint(out.position, position, quaternion, offset[0], offset[1], offset[2]);
    localPoint(out.target, position, quaternion, 0, 0.7, 2.6);
    out.fov = runtime.fov;
    out.positionSharpness = 9;
    out.targetSharpness = 8;
    out.rotationSharpness = 8;
    return out;
  }
};
var FreecamRig = class extends CameraRig {
  constructor() {
    super("Freecam");
  }
  compose(context, runtime, out) {
    out.position.x = runtime.freePosition.x;
    out.position.y = runtime.freePosition.y;
    out.position.z = runtime.freePosition.z;
    if (runtime.freeLookAt) {
      out.target.x = context.position.x;
      out.target.y = context.position.y + 0.8;
      out.target.z = context.position.z;
    } else {
      const e = runtime.freeEuler;
      out.target.x = out.position.x - Math.sin(e.y) * Math.cos(e.x);
      out.target.y = out.position.y + Math.sin(e.x);
      out.target.z = out.position.z - Math.cos(e.y) * Math.cos(e.x);
    }
    out.fov = runtime.fov;
    out.positionSharpness = 100;
    out.targetSharpness = runtime.freeLookAt ? 5 : 100;
    out.rotationSharpness = 100;
    return out;
  }
};
var createRigs = () => [
  new ChaseRig(),
  new ChaseRig(true),
  new FrontChaseRig(),
  new SideTrackingRig(),
  new OrbitRig(),
  new DroneRig(),
  new TracksideRig(),
  new FlyByRig(),
  new VehicleMountRig(),
  new FreecamRig()
];

// src/input.js
var InputController = class {
  constructor(owner) {
    this.owner = owner;
    this.keys = /* @__PURE__ */ new Set();
    this.speed = 18;
    this.mouseSensitivity = 22e-4;
    this.onKeyDown = this.onKeyDown.bind(this);
    this.onKeyUp = this.onKeyUp.bind(this);
    this.onMouseMove = this.onMouseMove.bind(this);
    this.onWheel = this.onWheel.bind(this);
    this.onBlur = () => this.keys.clear();
  }
  initialize(pml) {
    pml.registerBindCategory("Poly-Cam");
    const bind = (name, id, key, callback, filter = () => true) => pml.registerKeybind(name, id, "keydown", key, null, (event) => {
      if (!filter(event)) return;
      if (event.target?.closest?.("input, select, textarea, [contenteditable=true]") && !/^F\d+$/.test(event.code)) return;
      event.preventDefault();
      event.stopPropagation();
      if (event.repeat) return;
      callback(event);
    });
    bind("Toggle Poly-Cam", "polyCamToggle", "F6", () => this.owner.toggleEnabled());
    bind("Next camera", "polyCamNext", "F7", (e) => this.owner.nextMode(e.shiftKey ? -1 : 1));
    bind("Montage Mode", "polyCamMontage", "F8", () => this.owner.toggleMontage());
    bind("Clean Capture", "polyCamClean", "F9", () => this.owner.toggleCleanCapture());
    bind("Freecam", "polyCamFreecam", "F10", () => this.toggleFreecam());
    bind(
      "Hide/show Poly-Cam window",
      "polyCamWindowVisibility",
      "F4",
      () => this.owner.ui.toggleHidden(),
      (event) => !event.altKey && !event.ctrlKey && !event.metaKey && !event.shiftKey
    );
    window.addEventListener("keydown", this.onKeyDown, true);
    window.addEventListener("keyup", this.onKeyUp, true);
    window.addEventListener("mousemove", this.onMouseMove, true);
    window.addEventListener("wheel", this.onWheel, { capture: true, passive: false });
    window.addEventListener("blur", this.onBlur);
  }
  isFreecam() {
    return this.owner.enabled && this.owner.mode === "Freecam";
  }
  toggleFreecam() {
    this.owner.montage = false;
    this.owner.timelineState.playing = false;
    if (!this.owner.enabled) {
      this.owner.enabled = true;
      this.owner.activationSerial++;
    }
    this.owner.setMode(this.owner.mode === "Freecam" ? 0 : 9);
    this.owner.ui.refresh();
  }
  onKeyDown(event) {
    if (event.target?.closest?.("#poly-cam-panel, input, select, textarea, [contenteditable=true]")) return;
    if (event.code === "Escape" && this.isFreecam()) {
      event.preventDefault();
      this.owner.setMode(0);
      this.keys.clear();
      return;
    }
    if (this.isFreecam() && ["KeyW", "KeyA", "KeyS", "KeyD", "Space", "ControlLeft", "ControlRight", "ShiftLeft", "ShiftRight", "AltLeft", "AltRight"].includes(event.code)) {
      this.keys.add(event.code);
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  }
  onKeyUp(event) {
    this.keys.delete(event.code);
    if (this.isFreecam() && ["KeyW", "KeyA", "KeyS", "KeyD", "Space", "ControlLeft", "ControlRight", "ShiftLeft", "ShiftRight", "AltLeft", "AltRight"].includes(event.code)) {
      event.preventDefault();
      event.stopImmediatePropagation();
    }
  }
  onMouseMove(event) {
    if (!this.isFreecam() || !event.buttons || event.target?.closest?.("#poly-cam-panel")) return;
    const rt = this.owner.ui.activeRuntime;
    if (!rt) return;
    rt.freeEuler.y -= event.movementX * this.mouseSensitivity;
    rt.freeEuler.x = clamp(rt.freeEuler.x - event.movementY * this.mouseSensitivity, -1.45, 1.45);
    event.preventDefault();
    event.stopImmediatePropagation();
  }
  onWheel(event) {
    if (!this.isFreecam() || event.target?.closest?.("#poly-cam-panel")) return;
    this.speed = clamp(this.speed * (event.deltaY < 0 ? 1.15 : 0.87), 0.5, 250);
    event.preventDefault();
    event.stopImmediatePropagation();
  }
  stepFreecam(rt, dt) {
    this.owner.ui.activeRuntime = rt;
    const e = rt.freeEuler;
    const forward = this.keys.has("KeyW") ? 1 : this.keys.has("KeyS") ? -1 : 0;
    const side = this.keys.has("KeyD") ? 1 : this.keys.has("KeyA") ? -1 : 0;
    const vertical = this.keys.has("Space") ? 1 : this.keys.has("ControlLeft") || this.keys.has("ControlRight") ? -1 : 0;
    const multiplier = this.keys.has("ShiftLeft") || this.keys.has("ShiftRight") ? 4 : this.keys.has("AltLeft") || this.keys.has("AltRight") ? 0.2 : 1;
    const distance = this.speed * multiplier * dt;
    rt.freePosition.x += (-Math.sin(e.y) * forward + Math.cos(e.y) * side) * distance;
    rt.freePosition.z += (-Math.cos(e.y) * forward - Math.sin(e.y) * side) * distance;
    rt.freePosition.y += vertical * distance;
  }
  dispose() {
    window.removeEventListener("keydown", this.onKeyDown, true);
    window.removeEventListener("keyup", this.onKeyUp, true);
    window.removeEventListener("mousemove", this.onMouseMove, true);
    window.removeEventListener("wheel", this.onWheel, true);
    window.removeEventListener("blur", this.onBlur);
    this.keys.clear();
  }
};

// src/shot-director.js
var MONTAGE_PACES = {
  Cinematic: { minimum: 2.8, duration: 5.5 },
  Balanced: { minimum: 2.1, duration: 4.3 },
  Energetic: { minimum: 1.4, duration: 3.1 }
};
var family = (mode) => mode === 6 || mode === 7 ? "trackside" : mode === 4 || mode === 5 ? "wide" : mode === 8 ? "detail" : "follow";
var heading = (q) => Math.atan2(2 * (q.x * q.z + q.w * q.y), 1 - 2 * (q.x * q.x + q.y * q.y));
var angleDifference = (a, b) => Math.atan2(Math.sin(a - b), Math.cos(a - b));
var ShotDirector = class {
  constructor(random) {
    this.random = random;
  }
  createState() {
    return {
      time: 0,
      age: 0,
      turnRate: 0,
      verticalSpeed: 0,
      acceleration: 0,
      situation: "cruise",
      situationAge: 0,
      riseTime: 0,
      airborne: false,
      descending: false,
      landingUntil: 0,
      history: [],
      shot: null
    };
  }
  update(rt, context, { mode, pace }) {
    const state = rt.directorState ||= this.createState();
    const dt = context.dt;
    state.time += dt;
    state.age += dt;
    const alpha = 1 - Math.exp(-5 * dt);
    const turn = dt > 0 && rt.previousQuaternion ? angleDifference(heading(context.quaternion), heading(rt.previousQuaternion)) / dt : 0;
    const vertical = dt > 0 ? (context.position.y - rt.previousPosition.y) / dt : 0;
    state.turnRate += (clamp(turn, -4, 4) - state.turnRate) * alpha;
    state.verticalSpeed += (clamp(vertical, -80, 80) - state.verticalSpeed) * alpha;
    state.acceleration += (clamp(context.acceleration, -300, 300) - state.acceleration) * alpha;
    const q = context.quaternion;
    const expectedVertical = context.speed / 3.6 * 2 * (q.y * q.z - q.w * q.x);
    const rising = context.speed > 55 && state.verticalSpeed > 5 && state.verticalSpeed - expectedVertical > 3;
    state.riseTime = rising ? state.riseTime + dt : Math.max(0, state.riseTime - dt * 2);
    if (state.riseTime > 0.15) state.airborne = true;
    if (state.airborne && state.verticalSpeed < -3) state.descending = true;
    if (state.airborne && state.descending && state.verticalSpeed > -1) {
      state.airborne = false;
      state.descending = false;
      state.riseTime = 0;
      state.landingUntil = state.time + 0.65;
    }
    const banked = 1 - 2 * (q.x * q.x + q.z * q.z) < 0.35;
    const situation = banked ? "roll" : state.time < state.landingUntil ? "landing" : state.airborne ? "airborne" : context.speed < 12 ? "idle" : Math.abs(state.turnRate) > 0.28 && context.speed > 45 ? "corner" : state.acceleration > 24 && context.speed > 70 ? "acceleration" : context.speed > 155 ? "fast-straight" : "cruise";
    if (situation === state.situation) state.situationAge += dt;
    else {
      state.situation = situation;
      state.situationAge = 0;
    }
    const timing = MONTAGE_PACES[pace] || MONTAGE_PACES.Cinematic;
    if (!state.shot) return this.beginShot(state, rt, context, mode === 9 ? 0 : mode, timing);
    const shot = state.shot;
    if (situation === "roll" && shot.mode === 5) return shot;
    let passed = false;
    let lostFraming = false;
    if (shot.anchor) {
      const dx = shot.anchor.x - context.position.x, dz = shot.anchor.z - context.position.z;
      const remaining = dx * shot.forward.x + dz * shot.forward.z;
      passed = remaining < -Math.max(10, context.speed / 3.6 * 0.65);
      lostFraming = Math.hypot(dx, dz) > shot.distance + 85;
    }
    const recover = situation === "roll" && shot.mode !== 5 && state.situationAge > 0.12 && state.age > 0.8;
    const changedAction = situation !== shot.reason && state.situationAge > 0.3 && ["corner", "airborne", "landing", "acceleration"].includes(situation);
    if (!recover && !lostFraming && (state.age < timing.minimum || !passed && !changedAction && state.age < shot.duration)) return shot;
    const next = recover ? 5 : this.chooseMode(state, context.speed);
    return this.beginShot(state, rt, context, next, timing);
  }
  chooseMode(state, speed) {
    const candidates = state.situation === "idle" ? [[4, 5], [5, 3], [2, 2], [0, 1]] : state.situation === "roll" || state.situation === "airborne" ? [[5, 8], [3, 2], [0, 2]] : state.situation === "landing" ? [[0, 5], [1, 4], [3, 2]] : state.situation === "corner" ? [[3, 6], [5, 4], [0, 3], [2, 1]] : state.situation === "acceleration" ? [[1, 5], [3, 4], [7, 4], [8, 2], [0, 2]] : speed > 155 ? [[1, 5], [7, 5], [6, 4], [3, 3], [8, 2], [5, 2], [0, 2], [2, 1]] : [[0, 4], [3, 4], [2, 3], [5, 3], [4, 2], [6, speed > 65 ? 2 : 0]];
    const recent = state.history.slice(-3);
    const lastFamilies = state.history.slice(-2).map(family);
    const weighted = candidates.filter(([mode, weight]) => weight > 0 && mode !== state.shot.mode).map(([mode, weight]) => [mode, weight * (recent.includes(mode) ? 0.16 : 1) * (lastFamilies.length === 2 && lastFamilies.every((f) => f === family(mode)) ? 0.2 : 1)]);
    let choice = this.random() * weighted.reduce((sum, [, weight]) => sum + weight, 0);
    for (const [mode, weight] of weighted) {
      choice -= weight;
      if (choice <= 0) return mode;
    }
    return weighted.at(-1)?.[0] ?? 0;
  }
  beginShot(state, rt, context, mode, timing) {
    const random = (min, max) => min + this.random() * (max - min);
    const previous = state.shot;
    const side = Math.abs(state.turnRate) > 0.28 ? state.turnRate > 0 ? -1 : 1 : previous ? -previous.side : this.random() < 0.5 ? -1 : 1;
    const shot = {
      mode,
      side,
      reason: state.situation,
      duration: Math.max(timing.minimum + 0.5, timing.duration * random(0.8, 1.2)),
      transition: previous && [0, 1].includes(previous.mode) && [0, 1].includes(mode) ? "BLEND" : "CUT",
      fovOffset: [-5, 2, -13, -15, -8, -10, -30, -16, 3][mode] ?? 0
    };
    if (state.situation === "idle") shot.duration *= 1.4;
    if (mode === 0 || mode === 1) {
      shot.distance = mode === 1 ? random(7, 8.5) : random(8.5, 11);
      shot.height = mode === 1 ? random(0.85, 1.1) : random(2.2, 3.1);
      shot.lateral = side * random(0.2, 0.65);
      shot.lookAhead = random(3.5, 5);
    }
    if (mode === 2) {
      shot.distance = random(10, 13);
      shot.height = random(2.3, 3.3);
    }
    if (mode === 3) {
      shot.distance = random(8, 11);
      shot.height = random(2, 3);
      shot.longitudinal = random(-2, 2);
    }
    if (mode === 4) {
      shot.radius = random(11, 15);
      shot.height = random(3, 4.5);
      shot.orbitSpeed = random(0.16, 0.25);
      rt.orbitAngle = Math.PI + side * 0.45;
    }
    if (mode === 5) {
      shot.altitude = random(11, 16);
      shot.trail = random(6, 10);
    }
    if (mode === 8) {
      const mounts = context.speed > 120 ? ["Bonnet", "Front-left wheel", "Front-right wheel", "Roof"] : ["Bonnet", "Roof"];
      shot.mount = mounts[Math.floor(this.random() * mounts.length)];
      shot.duration = Math.max(timing.minimum, shot.duration * 0.7);
    }
    if (mode === 6 || mode === 7) {
      const yaw = heading(context.quaternion);
      let x = Math.sin(yaw), z = Math.cos(yaw);
      const dx = context.position.x - rt.previousPosition.x, dz = context.position.z - rt.previousPosition.z;
      const length = Math.hypot(dx, dz);
      if (length > 0.02 && context.speed > 30) {
        x = dx / length;
        z = dz / length;
      }
      shot.forward = { x, z };
      shot.distance = clamp(context.speed / 3.6 * random(1.1, 1.5), 22, 85);
      const lateral = side * (mode === 6 ? random(9, 13) : random(5, 8));
      shot.anchor = {
        x: context.position.x + x * shot.distance + z * lateral,
        y: context.position.y + (mode === 6 ? random(3.5, 5) : random(2.6, 3.6)),
        z: context.position.z + z * shot.distance - x * lateral
      };
      shot.duration = Math.max(timing.minimum + 0.5, Math.min(shot.duration, shot.distance / Math.max(8, context.speed / 3.6) + 1.8));
    }
    state.shot = shot;
    state.age = 0;
    state.history.push(mode);
    if (state.history.length > 6) state.history.shift();
    return shot;
  }
};

// src/ui.js
var STYLE = `
#poly-cam-panel{position:fixed;z-index:2147483000;top:12px;right:12px;width:min(292px,calc(100vw - 24px));max-height:calc(100vh - 24px);overflow:auto;padding:14px;color:#f4f7fa;background:rgba(10,16,22,.94);border:1px solid #ffffff30;border-radius:10px;font:12px/1.45 system-ui,sans-serif;box-shadow:0 8px 30px #0008}
#poly-cam-panel *{box-sizing:border-box;font-family:inherit}
#poly-cam-panel header{display:flex;justify-content:space-between;align-items:center;gap:12px;font-weight:800;letter-spacing:.1em;margin-bottom:8px}
#poly-cam-panel .header-controls{display:flex;align-items:center;gap:6px}
#poly-cam-panel button,#poly-cam-panel select,#poly-cam-panel input,#poly-cam-panel textarea{font:inherit;color:inherit;background:#202c36;border:1px solid #60707e;border-radius:5px;padding:6px;min-width:0}
#poly-cam-panel button{cursor:pointer}#poly-cam-panel button:hover{background:#334553}
#poly-cam-panel .state{font-size:10px}#poly-cam-panel .state[aria-pressed=true]{color:#85e0a3}
#poly-cam-panel .minimize{width:26px;height:26px;padding:0;font-size:18px;line-height:1}
#poly-cam-panel .hook-status{font-size:10px;color:#b2c4d0;margin:4px 0 10px}#poly-cam-panel .hook-status.active{color:#85e0a3}
#poly-cam-panel .row{display:flex;justify-content:space-between;align-items:center;gap:8px;margin:7px 0}
#poly-cam-panel select{width:150px}#poly-cam-panel input[type=range]{width:140px;padding:0}
#poly-cam-panel input[type=range]{appearance:none;height:6px;border:0;background:#60707e;outline:none}
#poly-cam-panel input[type=range]::-webkit-slider-thumb{appearance:none;width:14px;height:14px;border:1px solid #bdd0de;border-radius:50%;background:#8fdaff;box-shadow:none}
#poly-cam-panel input[type=range]::-moz-range-thumb{width:14px;height:14px;border:1px solid #bdd0de;border-radius:50%;background:#8fdaff}
#poly-cam-panel .mount{width:120px}#poly-cam-panel .actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:10px 0}
#poly-cam-panel .timeline{width:100%;resize:vertical;min-height:58px}#poly-cam-panel .timeline-load,#poly-cam-panel .bookmark{width:100%;margin:5px 0}
#poly-cam-panel .small{opacity:.75;font-size:10px}#poly-cam-panel .notice{color:#8fdaff;min-height:15px;letter-spacing:0}
#poly-cam-panel.collapsed{width:auto;padding:9px 12px}#poly-cam-panel.collapsed header{margin:0}#poly-cam-panel.collapsed>*:not(header){display:none!important}
#poly-cam-panel.panel-hidden{display:none!important}
body.poly-cam-clean #poly-cam-panel{display:none}`;
var UIController = class {
  constructor(owner) {
    this.owner = owner;
    this.root = null;
    this.style = null;
    this.lastCamera = null;
    this.activeRuntime = null;
    this.notice = "";
    this.hookStatus = "Waiting for a run";
    this.nativeHudHidden = false;
    this.collapsed = false;
    this.hidden = false;
  }
  mount() {
    if (this.root || !document.body) return;
    this.style = document.createElement("style");
    this.style.textContent = STYLE;
    document.head.appendChild(this.style);
    const root = document.createElement("section");
    root.id = "poly-cam-panel";
    root.setAttribute("aria-label", "Poly-Cam camera controls");
    root.innerHTML = `
            <header><span>POLY-CAM</span><span class="header-controls">
                <button class="state" data-action="toggle" title="Enable or disable Poly-Cam" aria-pressed="false">OFF</button>
                <button class="minimize" data-action="collapse" title="Minimize" aria-label="Minimize Poly-Cam" aria-expanded="true">−</button>
            </span></header>
            <div class="hook-status" role="status"></div>
            <div class="row"><label for="poly-cam-mode">Mode</label><select id="poly-cam-mode" class="mode">${MODES.map((m, i) => `<option value="${i}">${m}</option>`).join("")}</select></div>
            <div class="row"><label for="poly-cam-fov">FOV <span class="fov-label">72</span></label><input id="poly-cam-fov" class="fov" type="range" min="35" max="105" value="72"></div>
            <div class="row"><label>Transition</label><select class="transition"><option>CUT</option><option selected>BLEND</option></select></div>
            <div class="row"><label for="poly-cam-pace">Montage pace</label><select id="poly-cam-pace" class="montage-pace">${Object.keys(MONTAGE_PACES).map((p) => `<option>${p}</option>`).join("")}</select></div>
            <div class="row"><label>Side / mount</label><button data-action="side">Right</button><select class="mount"><option>Front bumper</option><option>Rear bumper</option><option>Bonnet</option><option selected>Roof</option><option>Front-left wheel</option><option>Front-right wheel</option><option>Rear wheel</option></select></div>
            <div class="row"><label>Fixed trackside orientation</label><input class="trackside-fixed" type="checkbox"></div>
            <div class="actions">
                <button data-action="previous">Previous</button><button data-action="next">Next</button>
                <button data-action="montage">Montage</button><button data-action="bookmark">Save Camera</button>
                <button data-action="trackside">Place Trackside</button><button data-action="clean">Clean Capture</button>
                <button data-action="timeline">Play Timeline</button><button data-action="timeline-reset">Reset Timeline</button>
            </div>
            <div class="row"><label>Loop timeline</label><input class="timeline-loop" type="checkbox"></div>
            <label for="poly-cam-timeline">Timeline JSON</label>
            <textarea id="poly-cam-timeline" class="timeline">[{"time":0,"mode":"Trackside Cam"},{"time":2.2,"mode":"Low Chase"},{"time":4.8,"mode":"Drone Cam"}]</textarea>
            <button class="timeline-load" data-action="timeline-load">Load timeline</button>
            <select class="bookmark" aria-label="Camera bookmarks"><option value="">Bookmarks</option></select>
            <div class="notice" role="status"></div>
            <div class="small">F6 toggle · F7 cameras · F8 montage · F9 clean · F10 freecam<br>F4 hide/show window · Freecam: drag to look · wheel changes speed</div>`;
    document.body.appendChild(root);
    this.root = root;
    root.classList.toggle("panel-hidden", this.hidden);
    root.addEventListener("click", (event) => {
      event.stopPropagation();
      const action = event.target.closest("button[data-action]")?.dataset.action;
      if (action === "toggle") this.owner.toggleEnabled();
      if (action === "collapse") this.toggleCollapsed();
      if (action === "next") this.owner.nextMode(1);
      if (action === "previous") this.owner.nextMode(-1);
      if (action === "montage") this.owner.toggleMontage();
      if (action === "bookmark") {
        if (!this.lastCamera) {
          this.setNotice("Enable Poly-Cam in a run before saving a camera.");
          return;
        }
        const name = prompt("Bookmark name", `Camera ${this.owner.bookmarks.length + 1}`);
        if (name) this.owner.saveBookmark(name);
      }
      if (action === "trackside") this.placeTrackside();
      if (action === "clean") this.owner.toggleCleanCapture();
      if (action === "timeline") {
        try {
          if (!this.owner.timeline.length) this.owner.loadTimeline(root.querySelector(".timeline").value);
          this.owner.toggleTimeline();
        } catch (error) {
          this.setNotice(error.message);
        }
      }
      if (action === "timeline-reset") {
        this.owner.resetTimeline();
        this.refresh();
      }
      if (action === "side") {
        this.owner.side *= -1;
        this.refresh();
      }
      if (action === "timeline-load") {
        try {
          this.owner.loadTimeline(root.querySelector(".timeline").value);
          this.setNotice("Timeline loaded.");
        } catch (error) {
          this.setNotice(error.message);
        }
      }
    });
    root.addEventListener("pointerdown", (event) => event.stopPropagation());
    root.addEventListener("wheel", (event) => event.stopPropagation());
    for (const type of ["keydown", "keyup"]) root.addEventListener(type, (event) => {
      if (!/^F\d+$/.test(event.code)) event.stopPropagation();
    });
    root.querySelector(".mode").addEventListener("change", (e) => this.owner.setMode(Number(e.target.value)));
    root.querySelector(".fov").addEventListener("input", (e) => {
      this.owner.baseFov = Number(e.target.value);
      root.querySelector(".fov-label").textContent = e.target.value;
    });
    root.querySelector(".mount").addEventListener("change", (e) => {
      this.owner.mount = e.target.value;
    });
    root.querySelector(".trackside-fixed").addEventListener("change", (e) => {
      this.owner.fixedTracksideOrientation = e.target.checked;
      if (this.activeRuntime) this.activeRuntime.tracksideFixed = e.target.checked;
    });
    root.querySelector(".timeline-loop").addEventListener("change", (e) => {
      this.owner.timelineState.loop = e.target.checked;
    });
    root.querySelector(".transition").addEventListener("change", (e) => {
      this.owner.transitionMode = e.target.value;
    });
    root.querySelector(".montage-pace").addEventListener("change", (e) => this.owner.setMontagePace(e.target.value));
    root.querySelector(".bookmark").addEventListener("change", (e) => {
      if (e.target.value !== "") this.owner.restoreBookmark(Number(e.target.value));
    });
    this.refresh();
    this.setHookStatus(this.hookStatus);
  }
  toggleCollapsed() {
    this.collapsed = !this.collapsed;
    this.root.classList.toggle("collapsed", this.collapsed);
    const button = this.root.querySelector(".minimize");
    button.textContent = this.collapsed ? "+" : "−";
    button.title = this.collapsed ? "Expand" : "Minimize";
    button.setAttribute("aria-label", this.collapsed ? "Expand Poly-Cam" : "Minimize Poly-Cam");
    button.setAttribute("aria-expanded", String(!this.collapsed));
  }
  toggleHidden() {
    this.hidden = !this.hidden;
    if (this.hidden && this.root?.contains(document.activeElement)) document.activeElement.blur();
    this.root?.classList.toggle("panel-hidden", this.hidden);
  }
  refresh() {
    if (!this.root) return;
    this.root.querySelector(".mode").value = String(this.owner.modeIndex);
    const state = this.root.querySelector(".state");
    state.textContent = this.owner.enabled ? "ON" : "OFF";
    state.setAttribute("aria-pressed", String(this.owner.enabled));
    this.root.querySelector("[data-action=montage]").textContent = this.owner.montage ? "Montage: ON" : "Montage";
    this.root.querySelector("[data-action=timeline]").textContent = this.owner.timelineState.playing ? "Pause Timeline" : "Play Timeline";
    this.root.querySelector(".fov").value = String(this.owner.baseFov);
    this.root.querySelector(".fov-label").textContent = String(this.owner.baseFov);
    this.root.querySelector(".mount").value = this.owner.mount;
    this.root.querySelector("[data-action=side]").textContent = this.owner.side > 0 ? "Right" : "Left";
    this.root.querySelector(".trackside-fixed").checked = this.owner.fixedTracksideOrientation;
    this.root.querySelector(".timeline-loop").checked = this.owner.timelineState.loop;
    this.root.querySelector(".transition").value = this.owner.transitionMode;
    this.root.querySelector(".montage-pace").value = this.owner.montagePace;
    this.root.querySelector(".bookmark").innerHTML = `<option value="">Bookmarks</option>${this.owner.bookmarks.map((b, i) => `<option value="${i}">${this.escape(b.name)}</option>`).join("")}`;
  }
  setClean(enabled) {
    if (!document.body) return;
    document.body.classList.toggle("poly-cam-clean", enabled);
    if (enabled) {
      this.previousCursor = document.body.style.cursor;
      document.body.style.cursor = "none";
    } else document.body.style.cursor = this.previousCursor || "";
    if (this.nativeHudHidden !== enabled) {
      window.dispatchEvent(new KeyboardEvent("keydown", { key: "h", code: "KeyH", bubbles: true, cancelable: true }));
      this.nativeHudHidden = enabled;
    }
  }
  setHookStatus(message) {
    this.hookStatus = message;
    const status = this.root?.querySelector(".hook-status");
    if (!status || status.textContent === message) return;
    if (status.textContent !== message) status.textContent = message;
    status.classList.toggle("active", message === "Camera connected");
  }
  setTransitionMode(mode) {
    if (this.root) this.root.querySelector(".transition").value = mode;
  }
  setNotice(message) {
    this.notice = message;
    if (this.root) this.root.querySelector(".notice").textContent = message;
  }
  placeTrackside() {
    if (this.owner.mode !== "Freecam" || !this.activeRuntime) {
      this.setNotice("Enter Freecam, position the camera, then place Trackside.");
      return;
    }
    const rt = this.activeRuntime;
    Object.assign(rt.trackside, rt.freePosition);
    const e = rt.freeEuler;
    rt.tracksideLook.x = rt.freePosition.x - Math.sin(e.y) * Math.cos(e.x) * 40;
    rt.tracksideLook.y = rt.freePosition.y + Math.sin(e.x) * 40;
    rt.tracksideLook.z = rt.freePosition.z - Math.cos(e.y) * Math.cos(e.x) * 40;
    rt.tracksideFixed = this.owner.fixedTracksideOrientation;
    rt.tracksidePlaced = true;
    this.owner.setMode(6);
    this.setNotice("Trackside camera placed.");
  }
  escape(value) {
    const span = document.createElement("span");
    span.textContent = value;
    return span.innerHTML;
  }
  dispose() {
    this.setClean(false);
    this.root?.remove();
    this.root = null;
    this.style?.remove();
    this.style = null;
  }
};

// src/poly-cam.js
var STORAGE_KEY = "poly-cam.v1";
function runtimeState() {
  return {
    initialized: false,
    fov: 72,
    side: 1,
    longitudinal: 0,
    orbitAngle: 0,
    orbitRadius: 11,
    orbitHeight: 3,
    orbitSpeed: 0.35,
    orbitDirection: 1,
    droneAltitude: 13,
    trackside: { x: 0, y: 0, z: 0 },
    tracksideLook: { x: 0, y: 0, z: 0 },
    tracksidePlaced: false,
    tracksideFixed: false,
    panSharpness: 4,
    flybyClock: 0,
    flybyAnchor: null,
    flybyDistance: 32,
    flybySide: 1,
    mount: "Roof",
    freePosition: { x: 0, y: 4, z: 10 },
    freeEuler: { x: -0.1, y: 0 },
    freeLookAt: false,
    previousSpeed: 0,
    acceleration: 0,
    previousPosition: { x: 0, y: 0, z: 0 },
    previousQuaternion: null,
    shotTime: 0,
    transition: null,
    lastFov: null,
    goalQuaternion: null,
    priorQuaternion: null,
    output: { position: { x: 0, y: 0, z: 0 }, target: { x: 0, y: 0, z: 0 }, fov: 72, positionSharpness: 4, targetSharpness: 4, rotationSharpness: 5 },
    smoothPosition: { x: 0, y: 0, z: 0 },
    smoothTarget: { x: 0, y: 0, z: 0 },
    directorState: null,
    montageShot: null,
    context: { position: null, quaternion: null, speed: 0, previousSpeed: 0, acceleration: 0, dt: 0 }
  };
}
var PolyCam = class {
  constructor() {
    this.enabled = false;
    this.montage = false;
    this.cleanCapture = false;
    this.rigs = createRigs();
    this.runtimes = /* @__PURE__ */ new WeakMap();
    this.nativeCameras = /* @__PURE__ */ new Map();
    this.bookmarks = [];
    this.timeline = [];
    this.timelineState = { playing: false, loop: false, time: 0, index: 0 };
    this.ui = new UIController(this);
    this.input = new InputController(this);
    this.baseFov = 72;
    this.side = 1;
    this.mount = "Roof";
    this.restoreSerial = 0;
    this.activationSerial = 0;
    this.pendingBookmark = null;
    this.lastShotAt = 0;
    this.directorSeed = 5370206;
    this.director = new ShotDirector(() => this.random());
    this.montagePace = "Cinematic";
    this.montageSerial = 0;
    this.transitionMode = "BLEND";
    this.fixedTracksideOrientation = false;
    this.cameraHookSeen = false;
    this.cameraHookErrorLogged = false;
  }
  initialize(pml) {
    this.pml = pml;
    globalThis.__polyCamControllerV1 = this;
    try {
      const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
      this.bookmarks = Array.isArray(saved.bookmarks) ? saved.bookmarks : [];
      this.directorSeed = Number.isInteger(saved.seed) ? saved.seed >>> 0 : this.directorSeed;
      if (Object.hasOwn(MONTAGE_PACES, saved.pace)) this.montagePace = saved.pace;
    } catch {
    }
    this.input.initialize(pml);
  }
  mountUI() {
    this.ui.mount();
  }
  get mode() {
    return this.rigs[this.modeIndex]?.name || MODES[0];
  }
  get modeIndex() {
    return this._modeIndex || 0;
  }
  set modeIndex(value) {
    this._modeIndex = (value + this.rigs.length) % this.rigs.length;
  }
  random() {
    let x = this.directorSeed >>> 0;
    x ^= x << 13;
    x ^= x >>> 17;
    x ^= x << 5;
    this.directorSeed = x >>> 0;
    return this.directorSeed / 4294967296;
  }
  setMode(index, { directed = false } = {}) {
    this.modeIndex = index;
    if (!directed && this.montage) {
      this.montage = false;
      this.montageSerial++;
    }
    this.lastShotAt = performance.now();
    this.ui.refresh();
  }
  nextMode(direction = 1) {
    this.setMode(this.modeIndex + direction);
  }
  toggleEnabled() {
    this.enabled = !this.enabled;
    if (this.enabled) this.activationSerial++;
    else {
      this.restoreNativeCameras();
      this.input.keys.clear();
    }
    this.ui.refresh();
  }
  toggleMontage() {
    this.montage = !this.montage;
    this.montageSerial++;
    if (this.montage) {
      this.timelineState.playing = false;
      this.input.keys.clear();
      if (this.mode === "Freecam") this.setMode(0, { directed: true });
      if (!this.enabled) this.toggleEnabled();
    }
    this.ui.refresh();
  }
  setMontagePace(pace) {
    if (!Object.hasOwn(MONTAGE_PACES, pace)) return;
    this.montagePace = pace;
    this.montageSerial++;
    this.persist();
    this.ui.refresh();
  }
  toggleCleanCapture() {
    this.cleanCapture = !this.cleanCapture;
    this.ui.setClean(this.cleanCapture);
  }
  selectCamera(camera) {
    this.selectedCamera = camera;
    if (camera !== this.activeCar?.cameraOrbit && camera !== this.activeCar?.cameraCockpit) {
      this.ui.setHookStatus("Waiting for a car camera");
      this.ui.lastCamera = null;
      this.ui.activeRuntime = null;
    }
  }
  handleCameraUpdate(car, dt) {
    if (car?.cameraOrbit !== this.selectedCamera && car?.cameraCockpit !== this.selectedCamera) return;
    this.cameraHookSeen = true;
    this.activeCar = car;
    this.ui.setHookStatus("Camera connected");
    this.ui.lastCamera = car.cameraOrbit;
    if (!this.enabled) return;
    if (!car?.cameraOrbit || typeof car.getPosition !== "function") {
      this.ui.setHookStatus("Camera target unavailable");
      return;
    }
    try {
      this.updateVehicleCamera(car, dt);
    } catch (error) {
      this.ui.setHookStatus("Camera error — see console");
      if (!this.cameraHookErrorLogged) {
        this.cameraHookErrorLogged = true;
        console.error("[Poly-Cam] Camera update failed:", error);
      }
    }
  }
  captureNativeCamera(camera) {
    if (!camera) return;
    let snapshot = this.nativeCameras.get(camera);
    if (!snapshot) {
      snapshot = { position: camera.position.clone(), quaternion: camera.quaternion.clone(), fov: camera.fov };
      this.nativeCameras.set(camera, snapshot);
    } else {
      snapshot.position.copy(camera.position);
      snapshot.quaternion.copy(camera.quaternion);
      snapshot.fov = camera.fov;
    }
  }
  restoreNativeCameras() {
    for (const [camera, snapshot] of this.nativeCameras) {
      camera.position.copy(snapshot.position);
      camera.quaternion.copy(snapshot.quaternion);
      camera.fov = snapshot.fov;
      camera.updateProjectionMatrix();
      camera.updateMatrix();
    }
    this.nativeCameras.clear();
  }
  updateVehicleCamera(car, dt) {
    if (!this.enabled) return;
    const camera = car.cameraOrbit;
    if (!camera || typeof car.getPosition !== "function") return;
    if (!car.hasFinished?.() || !this.nativeCameras.has(camera)) {
      this.captureNativeCamera(camera);
      this.captureNativeCamera(car.cameraCockpit);
    }
    let rt = this.runtimes.get(car);
    if (!rt) {
      rt = runtimeState();
      this.runtimes.set(car, rt);
    }
    const position = car.getPosition();
    const quaternion = car.getQuaternion();
    const speed = Number(car.getSpeedKmh()) || 0;
    const now = performance.now();
    const step = clamp(Number(dt) > 0 ? Number(dt) : (now - (rt.lastUpdateAt ?? now)) / 1e3, 0, 0.1);
    rt.lastUpdateAt = now;
    const context = rt.context;
    context.position = position;
    context.quaternion = quaternion;
    context.speed = speed;
    context.dt = step;
    if (!rt.initialized) {
      rt.initialized = true;
      rt.lastFov = camera.fov;
      rt.currentFov = camera.fov;
      rt.previousSpeed = speed;
      rt.smoothPosition.x = camera.position.x;
      rt.smoothPosition.y = camera.position.y;
      rt.smoothPosition.z = camera.position.z;
      rt.smoothTarget.x = position.x;
      rt.smoothTarget.y = position.y;
      rt.smoothTarget.z = position.z;
      rt.goalQuaternion = camera.quaternion.clone();
      rt.priorQuaternion = camera.quaternion.clone();
      rt.previousPosition.x = position.x;
      rt.previousPosition.y = position.y;
      rt.previousPosition.z = position.z;
      rt.previousQuaternion = quaternion.clone();
    }
    const carDx = position.x - rt.previousPosition.x, carDy = position.y - rt.previousPosition.y, carDz = position.z - rt.previousPosition.z;
    if (rt.activationSerial !== this.activationSerial || carDx * carDx + carDy * carDy + carDz * carDz > 400) {
      const reactivated = rt.activationSerial !== this.activationSerial;
      rt.smoothPosition.x = camera.position.x;
      rt.smoothPosition.y = camera.position.y;
      rt.smoothPosition.z = camera.position.z;
      rt.smoothTarget.x = position.x;
      rt.smoothTarget.y = position.y;
      rt.smoothTarget.z = position.z;
      rt.transition = null;
      rt.lastMode = this.modeIndex;
      rt.flybyAnchor = null;
      rt.activationSerial = this.activationSerial;
      rt.priorQuaternion.copy(camera.quaternion);
      rt.currentFov = camera.fov;
      rt.directorState = null;
      rt.montageShot = null;
      rt.previousPosition.x = position.x;
      rt.previousPosition.y = position.y;
      rt.previousPosition.z = position.z;
      rt.previousQuaternion.copy(quaternion);
      rt.previousSpeed = speed;
      if (reactivated && this.mode === "Freecam") {
        rt.freePosition.x = camera.position.x;
        rt.freePosition.y = camera.position.y;
        rt.freePosition.z = camera.position.z;
        camera.rotation.setFromQuaternion(camera.quaternion, "YXZ");
        rt.freeEuler.x = camera.rotation.x;
        rt.freeEuler.y = camera.rotation.y;
      }
    }
    this.ui.activeRuntime = rt;
    this.ui.lastCamera = camera;
    rt.fov = this.baseFov;
    rt.side = this.side;
    rt.mount = this.mount;
    let restoringBookmark = false;
    if (this.pendingBookmark && rt.restoreSerial !== this.restoreSerial) {
      restoringBookmark = true;
      const mark = this.pendingBookmark;
      rt.freePosition.x = mark.position.x;
      rt.freePosition.y = mark.position.y;
      rt.freePosition.z = mark.position.z;
      const q = mark.quaternion;
      rt.freeEuler.y = Math.atan2(2 * (q.w * q.y + q.x * q.z), 1 - 2 * (q.x * q.x + q.y * q.y));
      rt.freeEuler.x = Math.asin(clamp(2 * (q.w * q.x - q.z * q.y), -1, 1));
      rt.fov = mark.fov;
      this.baseFov = mark.fov;
      rt.restoreSerial = this.restoreSerial;
    }
    const previousSpeed = rt.previousSpeed;
    rt.acceleration = step > 0 ? (speed - rt.previousSpeed) / step : 0;
    rt.previousSpeed = speed;
    context.previousSpeed = previousSpeed;
    context.acceleration = rt.acceleration;
    rt.shotTime += step;
    this.advanceTimeline(step);
    rt.shotChanged = false;
    if (this.montage && !this.timelineState.playing) this.directMontage(rt, context);
    else rt.montageShot = null;
    if (rt.lastMode !== this.modeIndex || rt.shotChanged) {
      const from = rt.renderPosition || camera.position;
      const dx = from.x - rt.smoothPosition.x, dy = from.y - rt.smoothPosition.y, dz = from.z - rt.smoothPosition.z;
      const transition = rt.montageShot?.transition || this.transitionMode;
      rt.transition = transition === "BLEND" && dx * dx + dy * dy + dz * dz <= 2500 ? { fromX: from.x, fromY: from.y, fromZ: from.z, elapsed: 0 } : null;
      if (!rt.transition) {
        rt.cutPending = true;
        rt.smoothPosition.x = camera.position.x;
        rt.smoothPosition.y = camera.position.y;
        rt.smoothPosition.z = camera.position.z;
      }
      rt.lastMode = this.modeIndex;
      rt.flybyAnchor = null;
      if (this.mode === "Freecam" && !restoringBookmark) {
        rt.freePosition.x = from.x;
        rt.freePosition.y = from.y;
        rt.freePosition.z = from.z;
        camera.rotation.setFromQuaternion(rt.priorQuaternion, "YXZ");
        rt.freeEuler.x = camera.rotation.x;
        rt.freeEuler.y = camera.rotation.y;
      }
    }
    const rig = this.rigs[this.modeIndex];
    if (this.mode === "Freecam") this.input.stepFreecam(rt, step);
    const out = rig.compose(context, rt, rt.output);
    const cutCamera = rt.cutPending;
    if (rt.cutPending) {
      rt.smoothPosition.x = out.position.x;
      rt.smoothPosition.y = out.position.y;
      rt.smoothPosition.z = out.position.z;
      rt.smoothTarget.x = out.target.x;
      rt.smoothTarget.y = out.target.y;
      rt.smoothTarget.z = out.target.z;
      rt.cutPending = false;
    }
    if (this.mode === "Freecam" && rt.restoreSerial === this.restoreSerial && this.pendingBookmark) {
      out.position.x = rt.freePosition.x;
      out.position.y = rt.freePosition.y;
      out.position.z = rt.freePosition.z;
    }
    const alphaPos = 1 - Math.exp(-out.positionSharpness * step);
    const alphaTarget = 1 - Math.exp(-out.targetSharpness * step);
    rt.smoothPosition.x += (out.position.x - rt.smoothPosition.x) * alphaPos;
    rt.smoothPosition.y += (out.position.y - rt.smoothPosition.y) * alphaPos;
    rt.smoothPosition.z += (out.position.z - rt.smoothPosition.z) * alphaPos;
    rt.smoothTarget.x += (out.target.x - rt.smoothTarget.x) * alphaTarget;
    rt.smoothTarget.y += (out.target.y - rt.smoothTarget.y) * alphaTarget;
    rt.smoothTarget.z += (out.target.z - rt.smoothTarget.z) * alphaTarget;
    if (!finiteVector(rt.smoothPosition) || !finiteVector(rt.smoothTarget)) return;
    if (rt.transition) {
      rt.transition.elapsed += step;
      const t = smoothstep(clamp(rt.transition.elapsed / 0.45, 0, 1));
      camera.position.set(rt.transition.fromX + (rt.smoothPosition.x - rt.transition.fromX) * t, rt.transition.fromY + (rt.smoothPosition.y - rt.transition.fromY) * t, rt.transition.fromZ + (rt.smoothPosition.z - rt.transition.fromZ) * t);
      if (t >= 1) rt.transition = null;
    } else camera.position.set(rt.smoothPosition.x, rt.smoothPosition.y, rt.smoothPosition.z);
    camera.lookAt(rt.smoothTarget.x, rt.smoothTarget.y, rt.smoothTarget.z);
    rt.goalQuaternion.copy(camera.quaternion);
    const alphaRot = 1 - Math.exp(-out.rotationSharpness * step);
    if (cutCamera) rt.priorQuaternion.copy(rt.goalQuaternion);
    else rt.priorQuaternion.slerp(rt.goalQuaternion, alphaRot);
    camera.quaternion.copy(rt.priorQuaternion);
    const fov = clamp(out.fov, 25, 110);
    rt.currentFov = cutCamera ? fov : rt.currentFov + (fov - rt.currentFov) * (1 - Math.exp(-2.5 * step));
    camera.fov = rt.currentFov;
    camera.updateProjectionMatrix();
    rt.lastFov = camera.fov;
    camera.updateMatrix();
    if (!rt.renderPosition) rt.renderPosition = camera.position.clone();
    else rt.renderPosition.copy(camera.position);
    const cockpit = car.cameraCockpit;
    if (cockpit && cockpit !== camera) {
      cockpit.position.copy(camera.position);
      cockpit.quaternion.copy(camera.quaternion);
      cockpit.fov = camera.fov;
      cockpit.updateProjectionMatrix();
      cockpit.updateMatrix();
    }
    rt.previousQuaternion.copy(quaternion);
    rt.previousPosition.x = position.x;
    rt.previousPosition.y = position.y;
    rt.previousPosition.z = position.z;
    this.ui.lastCamera = camera;
    this.ui.activeRuntime = rt;
  }
  directMontage(rt, context) {
    if (rt.montageSerial !== this.montageSerial) {
      rt.directorState = null;
      rt.montageShot = null;
      rt.montageSerial = this.montageSerial;
    }
    const shot = this.director.update(rt, context, { mode: this.modeIndex, pace: this.montagePace });
    const changed = shot !== rt.montageShot;
    rt.montageShot = shot;
    rt.fov = clamp(this.baseFov + shot.fovOffset, 30, 100);
    rt.side = shot.side;
    rt.mount = shot.mount || this.mount;
    if (changed) {
      rt.shotChanged = true;
      this.setMode(shot.mode, { directed: true });
      this.persist();
    }
  }
  advanceTimeline(dt) {
    if (!this.timelineState.playing || !this.timeline.length) return;
    this.timelineState.time += dt;
    while (this.timelineState.index < this.timeline.length && this.timeline[this.timelineState.index].time <= this.timelineState.time) {
      const item = this.timeline[this.timelineState.index++];
      if (Number.isInteger(item.mode)) this.setMode(item.mode);
      else {
        const i = MODES.findIndex((name) => name.toLowerCase() === String(item.mode).toLowerCase());
        if (i >= 0) this.setMode(i);
      }
    }
    if (this.timelineState.index >= this.timeline.length) {
      if (this.timelineState.loop) {
        this.timelineState.time = 0;
        this.timelineState.index = 0;
      } else {
        this.timelineState.playing = false;
        this.ui.refresh();
      }
    }
  }
  toggleTimeline() {
    if (!this.timeline.length) return;
    if (this.timelineState.index >= this.timeline.length) this.resetTimeline();
    this.timelineState.playing = !this.timelineState.playing;
    if (this.timelineState.playing) {
      this.montage = false;
      if (!this.enabled) this.toggleEnabled();
    }
    this.ui.refresh();
  }
  resetTimeline() {
    this.timelineState.time = 0;
    this.timelineState.index = 0;
  }
  loadTimeline(json) {
    const parsed = JSON.parse(json);
    if (!Array.isArray(parsed)) throw new Error("Timeline must be a JSON array.");
    this.timeline = parsed.map((item) => {
      if (!item || !Number.isFinite(item.time) || item.time < 0) throw new Error("Each shot needs a non-negative time in seconds.");
      const mode = Number.isInteger(item.mode) ? item.mode : MODES.findIndex((name) => name.toLowerCase() === String(item.mode).toLowerCase());
      if (mode < 0 || mode >= MODES.length) throw new Error(`Unknown camera mode: ${item.mode}`);
      return { time: item.time, mode };
    }).sort((a, b) => a.time - b.time);
    this.resetTimeline();
  }
  saveBookmark(name = `Camera ${this.bookmarks.length + 1}`) {
    const record = this.ui.lastCamera;
    if (!record) return;
    this.bookmarks.push({ name, mode: this.mode, position: { x: record.position.x, y: record.position.y, z: record.position.z }, quaternion: { x: record.quaternion.x, y: record.quaternion.y, z: record.quaternion.z, w: record.quaternion.w }, fov: record.fov });
    this.persist();
    this.ui.refresh();
  }
  restoreBookmark(index) {
    const mark = this.bookmarks[index];
    if (!mark) return;
    this.pendingBookmark = mark;
    this.restoreSerial++;
    if (!this.enabled) this.toggleEnabled();
    this.montage = false;
    this.timelineState.playing = false;
    this.setMode(9);
  }
  persist() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify({ bookmarks: this.bookmarks, seed: this.directorSeed, pace: this.montagePace }));
    } catch {
    }
  }
  dispose() {
    this.enabled = false;
    this.cleanCapture = false;
    this.restoreNativeCameras();
    if (globalThis.__polyCamControllerV1 === this) delete globalThis.__polyCamControllerV1;
    this.input.dispose();
    this.ui.dispose();
    this.persist();
  }
};

// src/main.mod.js
function getMethodToken(pml, name) {
  const globalFunc = pml.getFromPolyTrackGlobal("globalFunc");
  const source = typeof globalFunc === "function" ? globalFunc.toString() : "";
  const signature = new RegExp(`\\b${name}\\s*\\([^)]*\\)\\s*\\{`).exec(source);
  if (!signature) throw new Error(`Could not find PolyTrack's ${name} method in globalFunc.`);
  const openBrace = source.indexOf("{", signature.index);
  let depth = 0;
  let quote = "";
  let escaped = false;
  let lineComment = false;
  let blockComment = false;
  for (let i = openBrace; i < source.length; i++) {
    const current = source[i];
    const next = source[i + 1];
    if (lineComment) {
      if (current === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      if (current === "*" && next === "/") {
        blockComment = false;
        i++;
      }
      continue;
    }
    if (quote) {
      if (escaped) {
        escaped = false;
        continue;
      }
      if (current === "\\") {
        escaped = true;
        continue;
      }
      if (current === quote) quote = "";
      continue;
    }
    if (current === "/" && next === "/") {
      lineComment = true;
      i++;
      continue;
    }
    if (current === "/" && next === "*") {
      blockComment = true;
      i++;
      continue;
    }
    if (current === "'" || current === '"' || current === "`") {
      quote = current;
      continue;
    }
    if (current === "{") depth++;
    if (current === "}" && --depth === 0) return source.slice(signature.index, i);
  }
  throw new Error(`Could not find the end of PolyTrack's ${name} method.`);
}
var PolyCamMod = class extends PolyMod {
  // globalFunc is executed between preInit and init. Patch it before execution;
  // changing its source during init does not change the already-created classes.
  preInit = (pml) => {
    pml.registerGlobalMixin({
      type: MixinType.INSERT,
      token: getMethodToken(pml, "updateCameras"),
      func: ";globalThis.__polyCamControllerV1?.handleCameraUpdate(this,arguments[0]);"
    });
    pml.registerGlobalMixin({
      type: MixinType.INSERT,
      token: getMethodToken(pml, "setCamera"),
      func: ";globalThis.__polyCamControllerV1?.selectCamera(arguments[0]);"
    });
  };
  init = (pml) => {
    this.pml = pml;
    this.controller = new PolyCam();
    this.controller.initialize(pml);
    if (document.body) this.controller.mountUI();
    else document.addEventListener("DOMContentLoaded", () => this.controller?.mountUI(), { once: true });
  };
  onGameLoad = () => this.controller?.mountUI();
  dispose = () => this.controller?.dispose();
};
var polyMod = new PolyCamMod();
export {
  polyMod
};
