import { build } from "esbuild";
import { readFile, mkdir, writeFile } from "node:fs/promises";

const { version } = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
await mkdir(new URL(`../${version}/`, import.meta.url), { recursive: true });
await build({
    entryPoints: ["src/main.mod.js"],
    outfile: `${version}/main.mod.js`,
    bundle: true,
    format: "esm",
    target: "es2022",
    external: ["https://cdn.polymodloader.com/*"],
    charset: "utf8",
    banner: { js: `// Poly-Cam ${version}. Generated by npm run build; edit src/ instead.` }
});
await writeFile(new URL(`../${version}/version.json`, import.meta.url), JSON.stringify({ targets: ["0.6.3"], dependencies: [], main: "main.mod.js" }, null, 2) + "\n");
const manifestPath = new URL("../manifest.json", import.meta.url);
const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
manifest.latest = { "0.6.3": version };
await writeFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
await writeFile(new URL("../latest.json", import.meta.url), JSON.stringify(manifest.latest, null, 2) + "\n");
